cart/urls.py
from django.urls import path

from cart import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart, name='cart'),
    path('add/', views.cartAdd, name='cart_add'),
    path('update/', views.cartUpdate, name='cart_update'),
    path('delete/', views.cartDelete, name='cart_delete'),
]

checkout/urls.py
from django.urls import path

from checkout import views, payment as paymentViews

app_name = "checkout"

urlpatterns = [
    path("delivery-choices", views.deliveryChoices, name="delivery_choices"),
    path("cart-update-delivery", views.cartUpdateDelivery, name="update_delivery"),
    path("delivery-address", views.deliveryAddress, name="delivery_address"),
    path("payment-selection", views.paymentSelection, name="payment_selection"),
    path("payment-successful", views.paymentSuccessful, name="payment_successful"),
    path('webhook', paymentViews.stripeWebhook, name="payment_webhook"),
]

core/urls.py
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('orders/', include('orders.urls', namespace='orders')),
    path('shopping-cart/', include('cart.urls', namespace='cart')),
    path('account/', include('account.urls', namespace='account')),
    path('checkout/', include('checkout.urls', namespace='checkout')),
    path('', include('store.urls', namespace='store')),
    path("__debug__/", include(debug_toolbar.urls)),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path

from . import views

app_name = 'store'

urlpatterns = [
    path('', views.products, name='products'),
    path('<slug:slug>/', views.productDetail, name='product_detail'),
    path('shop/<slug:category_slug>/', views.categoryProducts, name='category_products'),
]

cart/models.py
from django.db import models

from store import models as productModels 
from django.conf import settings

class Cart(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, blank=False, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True, editable=False)

    class Meta:
        get_latest_by = "created_at"

class CartItem(models.Model):
    cart = models.ForeignKey(Cart, blank=False, on_delete=models.CASCADE, related_name="cart_items")
    product = models.ForeignKey(productModels.Product, blank=False, on_delete=models.CASCADE, related_name="cart_product")
    quantity = models.IntegerField(null=False, blank=False)

cart/views.py
from django.shortcuts import render, get_object_or_404
from django.http import JsonResponse, HttpResponseBadRequest
from django.views.decorators import http as httpDecorators
from django.contrib import auth

from cart.cart import CartProcessor
from cart import exceptions
from store import models

@httpDecorators.require_GET
@auth.decorators.login_required
def cart(request):
    cart = CartProcessor(request)
    return render(request, 'cart/summary.html', {'cart': cart}) 


@httpDecorators.require_POST
def cartAdd(request):
    try:
        cart = CartProcessor(request) 

        productId = int(request.POST.get('product_id'))
        productQuantity = int(request.POST.get('product_quantity'))
        product = get_object_or_404(models.Product, id= productId)
        cart.create(product= product, quantity= productQuantity)
        
        return JsonResponse({'quantity': cart.__len__()})
    except exceptions.CartException as err:
        return HttpResponseBadRequest(err.message)
        

@httpDecorators.require_POST
def cartDelete(request):
    try:
        cart = CartProcessor(request)
        productId = int(request.POST.get('product_id'))
        cart.delete(product= productId)

        return JsonResponse({'quantity': cart.__len__(), 'subtotal': cart.get_total_price}) 
    except exceptions.CartException as err:
        return HttpResponseBadRequest(err.message)


@httpDecorators.require_POST
def cartUpdate(request):
    try:
        cart = CartProcessor(request)
        productId = int(request.POST.get('product_id'))
        productQuantity = int(request.POST.get('product_quantity'))
        cart.update(productId= productId, quantity= productQuantity)

        return JsonResponse({'quantity': cart.__len__(), 'subtotal': cart.get_total_price}) 
    except exceptions.CartException as err:
        return HttpResponseBadRequest(err.message)  

cart/templates/cart/summary.html
{% extends "app.html" %}
{% load static %}
{% block title %}Shopping Cart Summary{% endblock %}
{% block stylesheet %}
<link rel="stylesheet" href="{% static 'css/cart.css' %}">
{% endblock %}

{% block content %}

<div class="container py-4 text-light">
  <div class="col-12">
    <h1 class="h2">Your Cart</h1>
  </div>
  <div class="col-12">
    <p>Manage your <b>items</b> in your cart</p>
  </div>
  <hr />
</div>
<div class="container py-4">

  <div class="row g-3">
    {% if cart|length == 0 %}
    <div class="col-12"><p>No product in the cart</p></div>
    {% else %}
    <div class="col-12 text-light p-3 d-flex justify-content-between">
      <div>
        <h3 class="">Sub Total: <span class="fw-bold">£</span>
          <div id="subtotal" class="d-inline-flex fw-bold">{{cart.get_subtotal_price}}</div>
        </h3>
      </div>
    </div>
    <div class="col-md-5 col-lg-4 order-md-last p-1 order-3">
      <div class="d-grid gap-2 ">
        <a role="button" href="{% url 'checkout:delivery_choices' %}" class="btn btn-success fw-bold" type="button">Checkout</a>
        <a href="{% url 'store:products' %}" class="btn btn-light" type="button">Save for later</a>
      </div>
    </div>
    <div class="col-md-7 col-lg-8 p-1">

      {% for item in cart %}
      {% with product=item.product %}

      <div class="card mb-3 border-0 product-item" data-index="{{product.id}}">
        <div class="row g-0">
          <div class="col-md-2 d-none d-md-block">
            {% for image in product.product_image.all %}
            {% if image.is_feature%}
            <img class="img-fluid" alt="Responsive image" src="{{ image.image.url }}" alt="{{ image.image.alt_text }}">
            {% endif %}
            {% endfor %}
          </div>
          <div class="col-md-10 ps-md-3">
            <div class="card-body p-1">
              <a class="text-decoration-none text-reset" href="{{item.product.get_absolute_url}}">
                <p class="card-text pb-3">{{product.title}}</p>
              </a>
              <label for="select">Quantity</label>
              <select id="select{{product.id}}" style="width:50px;height:31px;">
                <option value="" selected disabled hidden>{{item.quantity}}</option>
                <option value="">1</option>
                <option value="">2</option>
                <option value="">3</option>
                <option value="">4</option>
              </select>
              <a type="button" id="update-button" data-index="{{product.id}}"
                class="update-button btn btn-primary text-decoration-none small ps-3">Update</a>
              <a type="button" id="delete-button" data-index="{{product.id}}"
                class="delete-button btn btn-danger text-decoration-none small">Delete</a>
            </div>
          </div>
        </div>
      </div>
      {% endwith %}
      {% endfor %}
    </div>
    {% endif %}
  </div>

</div>
{% endblock %}

{% block scripts %}
<script>
  // Delete Item
  $(document).on('click', '.delete-button', function (e) {
    e.preventDefault();
    var productId = $(this).data('index');
    $.ajax({
      type: 'POST',
      url: '{% url "cart:cart_delete" %}',
      data: {
        product_id: $(this).data('index'),
        csrfmiddlewaretoken: "{{csrf_token}}",
      },
      success: function (json) {
        $('.product-item[data-index="' + productId + '"]').remove();
        document.getElementById("subtotal").innerHTML = json.subtotal;
        document.getElementById("cart-quantity").innerHTML = json.quantity
      },
      error: function (xhr, errmsg, err) {}
    });
  })

  // Update Item
  $(document).on('click', '.update-button', function (e) {
    e.preventDefault();
    var productId = $(this).data('index');
    $.ajax({
      type: 'POST',
      url: '{% url "cart:cart_update" %}',
      data: {
        product_id: $(this).data('index'),
        product_quantity: $('#select' + productId + ' option:selected').text(),
        csrfmiddlewaretoken: "{{csrf_token}}",
      },
      success: function (json) {
        document.getElementById("cart-quantity").innerHTML = json.quantity
        document.getElementById("subtotal").innerHTML = json.subtotal
      },
      error: function (xhr, errmsg, err) {}
    });
  })
</script>
{% endblock%}