account/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from django.views.generic import TemplateView

from . import views
from .forms import PwdResetConfirmForm, PwdResetForm, UserLoginForm

app_name = 'account'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='account/auth/login.html',
                                                form_class=UserLoginForm), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/account/login/'), name='logout'),
    path('register/', views.register, name='register'),
    path('activate/<slug:uidb64>/<slug:token>/', views.activate, name='activate'),
    # Reset password
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name="account/auth/password_reset_form.html",
                                                                 success_url='password_reset_email_confirm',
                                                                 email_template_name='account/auth/password_reset_email.html',
                                                                 form_class=PwdResetForm), name='pwdreset'),
    path('password_reset_confirm/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name='account/auth/password_reset_confirm.html',
                                                                                                success_url='password_reset_complete/',
                                                                                                form_class=PwdResetConfirmForm),
         name="password_reset_confirm"),
    path('password_reset/password_reset_email_confirm/',
         TemplateView.as_view(template_name="account/auth/password_reset_status.html"), name='password_reset_done'),
    path('password_reset_confirm/Mg/password_reset_complete/',
         TemplateView.as_view(template_name="account/auth/password_reset_status.html"), name='password_reset_complete'),

    path('dashboard/', views.dashboard, name='dashboard'),
    path('profile/edit/', views.edit, name='edit'),
    path('profile/delete/', views.delete, name='delete'),
    path('profile/delete_confirm/', TemplateView.as_view(template_name="account/user/delete_confirm.html"), name='delete_confirmation'),
    path("addresses/", views.addresses, name="addresses"),
    path("add_address/", views.addAddress, name="add_address"),
    path("addresses/edit/<slug:id>/", views.editAddress, name="edit_address"),
    path("addresses/delete/<slug:id>/", views.deleteAddress, name="delete_address"),
    path("addresses/set_default/<slug:id>/", views.setDefaultAddress, name="set_default_address"),
    path("wishlist/", views.wishlist, name="wishlist"),
    path("wishlist/toggle/<int:id>", views.addToWishlist, name="toggle_wishlist"),
    path("orders/", views.ordersView, name="orders"),
]

cart/urls.py
from django.urls import path

from cart import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart, name='cart'),
    path('add/', views.cartAdd, name='cart_add'),
    path('update/', views.cartUpdate, name='cart_update'),
    path('delete/', views.cartDelete, name='cart_delete'),
]

core/urls.py
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('orders/', include('orders.urls', namespace='orders')),
    path('shopping-cart/', include('cart.urls', namespace='cart')),
    path('account/', include('account.urls', namespace='account')),
    path('checkout/', include('checkout.urls', namespace='checkout')),
    path('', include('store.urls', namespace='store')),
    path("__debug__/", include(debug_toolbar.urls)),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path

from . import views

app_name = 'store'

urlpatterns = [
    path('', views.products, name='products'),
    path('<slug:slug>/', views.productDetail, name='product_detail'),
    path('shop/<slug:category_slug>/', views.categoryProducts, name='category_products'),
]

store/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from mptt.models import MPTTModel, TreeForeignKey


class Category(MPTTModel):
    name = models.CharField(
        verbose_name=_("Category Name"),
        help_text=_("Required and unique"),
        max_length=255,
        unique=True,
    )
    slug = models.SlugField(verbose_name=_("Category safe URL"), max_length=255, unique=True)
    parent = TreeForeignKey("self", on_delete=models.CASCADE, null=True, blank=True, related_name="children")
    is_active = models.BooleanField(default=True)

    class MPTTMeta:
        order_insertion_by = ["name"]

    class Meta:
        verbose_name = _("Category")
        verbose_name_plural = _("Categories")

    def get_absolute_url(self):
        return reverse("store:category_products", args=[self.slug])

    def __str__(self):
        return self.name


class ProductType(models.Model):
    name = models.CharField(verbose_name=_("Product Name"), help_text=_("Required"), max_length=255, unique=True)
    is_active = models.BooleanField(default=True)

    class Meta:
        verbose_name = _("Product Type")
        verbose_name_plural = _("Product Types")

    def __str__(self):
        return self.name


class ProductManager(models.Manager):
    def get_queryset(self):
        return super(ProductManager, self).get_queryset().filter(is_active=True)

class Product(models.Model):
    product_type = models.ForeignKey(ProductType, on_delete=models.RESTRICT, related_name="product_type")
    category = models.ForeignKey(Category, on_delete=models.RESTRICT, related_name="category")
    title = models.CharField(
        verbose_name=_("title"),
        help_text=_("Required"),
        max_length=255,
    )
    description = models.TextField(verbose_name=_("description"), help_text=_("Not Required"), blank=True)
    slug = models.SlugField(max_length=255)
    regular_price = models.DecimalField(
        verbose_name=_("Regular price"),
        help_text=_("Maximum 999.99"),
        error_messages={
            "name": {
                "max_length": _("The price must be between 0 and 999.99."),
            },
        },
        max_digits=5,
        decimal_places=2,
    )
    discount_price = models.DecimalField(
        verbose_name=_("Discount price"),
        help_text=_("Maximum 999.99"),
        error_messages={
            "name": {
                "max_length": _("The price must be between 0 and 999.99."),
            },
        },
        default=0,
        blank=True,
        max_digits=5,
        decimal_places=2,
    )
    is_active = models.BooleanField(
        verbose_name=_("Product visibility"),
        help_text=_("Change product visibility"),
        default=True,
    )
    created_at = models.DateTimeField(_("Created at"), auto_now_add=True, editable=False)
    updated_at = models.DateTimeField(_("Updated at"), auto_now=True)
    user_wishlist = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="user_wishlist", blank=True)

    products = ProductManager()
    class Meta:
        ordering = ("-created_at",)
        verbose_name = _("Product")
        verbose_name_plural = _("Products")

    def get_absolute_url(self):
        return reverse("store:product_detail", args=[self.slug])

    def __str__(self):
        return self.title


class ProductSpecification(models.Model):
    product_type = models.ForeignKey(ProductType, on_delete=models.RESTRICT)
    name = models.CharField(verbose_name=_("Name"), help_text=_("Required"), max_length=255)

    class Meta:
        verbose_name = _("Product Specification")
        verbose_name_plural = _("Product Specifications")

    def __str__(self):
        return self.name
        
class ProductSpecificationValue(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name="product_specification_value")
    specification = models.ForeignKey(ProductSpecification, on_delete=models.RESTRICT, related_name="prod_specification")
    value = models.CharField(
        verbose_name=_("value"),
        help_text=_("Product specification value (maximum of 255 words"),
        max_length=255,
    )

    class Meta:
        verbose_name = _("Product Specification Value")
        verbose_name_plural = _("Product Specification Values")

    def __str__(self):
        return self.value


class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name="product_image")
    image = models.ImageField(
        verbose_name=_("image"),
        help_text=_("Upload a product image"),
        upload_to="images/",
        default="images/default.png",
    )
    alt_text = models.CharField(
        verbose_name=_("Alturnative text"),
        help_text=_("Please add alturnative text"),
        max_length=255,
        null=True,
        blank=True,
    )
    is_feature = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True, editable=False)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = _("Product Image")
        verbose_name_plural = _("Product Images")

store/views.py
from django.shortcuts import get_object_or_404, render
from django.views.decorators import http
from django.http import HttpResponseNotFound
from store import models


@http.require_GET
def products(request):
    products = models.Product.products.prefetch_related('product_image').all()
    return render(request, 'store/index.html', {'products': products})

@http.require_GET
def categoryProducts(request, category_slug=None):
    category = get_object_or_404(models.Category, slug=category_slug)
    products = models.Product.products.prefetch_related('product_image').filter(
        category=models.Category.objects.get(slug=category_slug)
    )
    return render(request, 'store/category.html', {'category': category, 'products': products})

@http.require_GET
def productDetail(request, slug):
    try:
        product = models.Product.products.select_related('product_type','category').prefetch_related('product_image', 'product_specification_value').get(slug=slug)
        
        if request.user.is_authenticated:
            wishlist = [item.id for item in models.Product.products.filter(user_wishlist=request.user)]
        else:
            wishlist = []
        return render(request, 'store/detail.html', {'product': product, 'wishlist':wishlist})
    except models.Product.DoesNotExist:
        return HttpResponseNotFound("Product not found")
    

store/templates/store/category.html
{% extends "app.html" %}
{% load static %}
{% block title %}
{% if category %}{{ category.name }}{% else %}Products{% endif %}
{% endblock %}
{% block content %}

<div class="album py-5">
  <div class="container">

    <div class="pb-3 h3 text-light">{{category.name|title}}</div>
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-4 g-3">

      {% if not products %}
      <div class="col-12">
        <p>No products. <a href="{% url 'store:products '%}">Home</a></p> 
      </div>
      {% else %}
      {% for product in products %}
      <div class="col">
        <div class="card shadow-sm">
          {% for image in product.product_image.all %}
          {% if image.is_feature %}
          <img class="img-fluid" alt="Responsive image" src="{{ image.image.url }}"
            alt="{{ image.image.alt_text }}">
          {% endif %}
          {% endfor %}
          <div class="card-body">
            <p class="card-text">
              <a class="text-dark text-decoration-none" href="{{ product.get_absolute_url }}">{{ product.title|slice:":50" }}</a>
            </p>
            <div class="fw-bold">${{product.regular_price}}</div>
          </div>
        </div>
      </div>
      {% endfor %}
      {% endif %}

    </div>
  </div>
</div>


{% endblock %}

store/templates/store/detail.html
{% extends "app.html" %}
{% load static %}
{% block title %}
{{ product.title }}
{% endblock %}
{% block stylesheet %}
<link rel="stylesheet" href="{% static 'css/store.css' %}">
{% endblock %}
{% block content %}

<div class="container py-4">
    {% if messages %}
    <div class="alert alert-warning alert-{{ message.tags }}" role="alert">
        {% for message in messages  %}
        {{message|safe}} - <a href="{% url "account:wishlist" %}" class="alert-link">Your Wishlist</a>.
        {% endfor %}
    </div>
    {% endif %}
    <div class="row g-3">
        <div class="col-md-5 ps-3 col-lg-5 order-md-last p-0 order-1">
            <div class="d-grid gap-2">
                <div class="d-flex d-flex-inline justify-content-between">
                    <div class="text-light"><span class="h3">${{ product.regular_price }}</span>
                        <p>includes tax</p>
                    </div>
                    {% if product.discount_price %}<div class="text-light"><span class="h5">${{ product.discount_price }}</span>
                        <p>discount</p>
                    </div>{% endif %}
                    <div>
                        <label for="select" class="text-light">Quantity</label>
                        <select id="select" class="h6 store-select-dropdown">
                            <option value="1">1</option>
                            <option value="2">2</option>
                            <option value="3">3</option>
                            <option value="4">4</option>
                        </select>
                    </div>
                </div>
                <hr>
                <button type="button" id="add-button" value="{{product.id}}" class="btn btn-success fw500">Add to
                    basket</button>
                <a href="{% url "account:toggle_wishlist" product.id  %}" class="btn {% if product.id in wishlist %}btn-secondary{% else %}btn-primary{% endif %} fw500" role="button" aria-disabled="true">
                    {% if product.id in wishlist %}
                    Remove from Wish List
                    {% else %}
                    Add to Wish List
                    {% endif %}
                </a>
            </div>
        </div>
        <div class="col-md-7 col-lg-7 p-0">
            <div class="card mb-3 border-0">
                <div class="row g-0">
                    <div class="col-md-12">
                        <div class="card-body p-2">
                            <h1 class="mb-0 h2 pe-4 pb-4">{{ product.title }}</h1>
                            <h5 class="mb-0 pe-4 pb-4 text-decoration-none"><a href="{% url 'store:category_products' category_slug=product.category.slug %}">{{ product.category.name }}</a></h4>
                            <h5 class="mb-0 pe-4 pb-4 text-decoration-none">{{product.product_type.name}}</h4>
                            <div class="bg-light">

                                {% for image in product.product_image.all %}
                                {% if image.is_feature %}
                                <img class="img-fluid mx-auto d-block" width="200px" alt="Responsive image"
                                    src="{{ image.image.url }}" alt="{{ image.image.alt_text }}">
                                {% else %}
                                <img class="img-fluid d-block-inline pt-3" width="100px" alt="Responsive image"
                                    src="{{ image.image.url }}" alt="{{ image.image.alt_text }}">
                                {% endif %}
                                {% endfor %}

                            </div>
                            <p class="card-text px-3 py-4">{{product.description}}</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    {% endblock %}

    {% block scripts %}
    <script>
        $(document).on('click', '#add-button', function (e) {
            e.preventDefault();
            $.ajax({
                type: 'POST',
                url: '{% url "cart:cart_add" %}',
                data: {
                    product_id: $('#add-button').val(),
                    product_quantity: $('#select option:selected').val(),
                    csrfmiddlewaretoken: "{{csrf_token}}",
                },
                success: function (json) {
                    document.getElementById("cart-quantity").innerHTML = json.quantity
                },
                error: function (xhr, errmsg, err) {}
            });
        })
    </script>
    {% endblock %}

store/templates/store/index.html
{% extends "app.html" %} {% load static %} {% block title %}Home{% endblock %}
{% block content %}

<div class="section-top">
  <div class="landing-cover">
    <div class="landing-content">
      <h1 class="banner-header text-light">Memory is not what the heart desires. That is only a mirror</h1>
      {% if not user.is_authenticated %}
    <a class="btn btn-light" href="{% url 'account:login' %}"
      >Make an account</a
    >
    {% endif %}
  </div>
  </div>
</div>

<div class="album py-5">
  <div class="container">
    <div class="pb-3 h3 text-center text-light">All Products</div>
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-4 g-3">
      {% if not products %}
      <div class="col-12">
        <p>No products</p>
      </div>
      {% else %} {% for product in products %}
      <div class="col">
        <div class="card shadow-sm">
          {% for image in product.product_image.all %} {% if image.is_feature %}
          <img
            class="img-fluid"
            alt="Responsive image"
            src="{{ image.image.url }}"
            alt="{{ image.image.alt_text }}"
          />
          {% endif %} {% endfor %}
          <div class="card-body">
            <p class="card-text">
              <a
                class="text-dark text-decoration-none"
                href="{{ product.get_absolute_url }}"
                >{{ product.title|slice:":50" }}</a
              >
            </p>
            <div class="fw-bold">${{product.regular_price}}</div>
          </div>
        </div>
      </div>
      {% endfor %} {% endif %}
    </div>
  </div>
</div>

{% endblock %}