account/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from django.views.generic import TemplateView

from . import views
from .forms import PwdResetConfirmForm, PwdResetForm, UserLoginForm

app_name = 'account'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='account/auth/login.html',
                                                form_class=UserLoginForm), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/account/login/'), name='logout'),
    path('register/', views.register, name='register'),
    path('activate/<slug:uidb64>/<slug:token>/', views.activate, name='activate'),
    # Reset password
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name="account/auth/password_reset_form.html",
                                                                 success_url='password_reset_email_confirm',
                                                                 email_template_name='account/auth/password_reset_email.html',
                                                                 form_class=PwdResetForm), name='pwdreset'),
    path('password_reset_confirm/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name='account/auth/password_reset_confirm.html',
                                                                                                success_url='password_reset_complete/',
                                                                                                form_class=PwdResetConfirmForm),
         name="password_reset_confirm"),
    path('password_reset/password_reset_email_confirm/',
         TemplateView.as_view(template_name="account/auth/password_reset_status.html"), name='password_reset_done'),
    path('password_reset_confirm/Mg/password_reset_complete/',
         TemplateView.as_view(template_name="account/auth/password_reset_status.html"), name='password_reset_complete'),

    path('dashboard/', views.dashboard, name='dashboard'),
    path('profile/edit/', views.edit, name='edit'),
    path('profile/delete/', views.delete, name='delete'),
    path('profile/delete_confirm/', TemplateView.as_view(template_name="account/user/delete_confirm.html"), name='delete_confirmation'),
    path("addresses/", views.addresses, name="addresses"),
    path("add_address/", views.addAddress, name="add_address"),
    path("addresses/edit/<slug:id>/", views.editAddress, name="edit_address"),
    path("addresses/delete/<slug:id>/", views.deleteAddress, name="delete_address"),
    path("addresses/set_default/<slug:id>/", views.setDefaultAddress, name="set_default_address"),
    path("wishlist/", views.wishlist, name="wishlist"),
    path("wishlist/toggle/<int:id>", views.addToWishlist, name="toggle_wishlist"),
    path("orders/", views.ordersView, name="orders"),
]

cart/urls.py
from django.urls import path

from cart import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart, name='cart'),
    path('add/', views.cartAdd, name='cart_add'),
    path('update/', views.cartUpdate, name='cart_update'),
    path('delete/', views.cartDelete, name='cart_delete'),
]

checkout/urls.py
from django.urls import path

from checkout import views, payment as paymentViews

app_name = "checkout"

urlpatterns = [
    path("delivery-choices", views.deliveryChoices, name="delivery_choices"),
    path("cart-update-delivery", views.cartUpdateDelivery, name="update_delivery"),
    path("delivery-address", views.deliveryAddress, name="delivery_address"),
    path("payment-selection", views.paymentSelection, name="payment_selection"),
    path("payment-successful", views.paymentSuccessful, name="payment_successful"),
    path('webhook', paymentViews.stripeWebhook, name="payment_webhook"),
]

core/urls.py
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('orders/', include('orders.urls', namespace='orders')),
    path('shopping-cart/', include('cart.urls', namespace='cart')),
    path('account/', include('account.urls', namespace='account')),
    path('checkout/', include('checkout.urls', namespace='checkout')),
    path('', include('store.urls', namespace='store')),
    path("__debug__/", include(debug_toolbar.urls)),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path

from . import views

app_name = 'orders'

urlpatterns = [
    path('add/', views.add, name='add'),
]

store/urls.py
from django.urls import path

from . import views

app_name = 'store'

urlpatterns = [
    path('', views.products, name='products'),
    path('<slug:slug>/', views.productDetail, name='product_detail'),
    path('shop/<slug:category_slug>/', views.categoryProducts, name='category_products'),
]

checkout/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _


class DeliveryOptions(models.Model):
    
    class DeliveryChoices(models.TextChoices):
        STORE = 'IS', _('In Store')
        HOME = 'HD', _('Home Delivery')
        DIGITAL = 'DD', _('Digital Delivery')

    delivery_name = models.CharField(
        verbose_name=_("delivery_name"),
        help_text=_("Required"),
        max_length=255,
    )
    delivery_price = models.DecimalField(
        verbose_name=_("delivery price"),
        help_text=_("Maximum 999.99"),
        error_messages={
            "name": {
                "max_length": _("The price must be between 0 and 999.99."),
            },
        },
        max_digits=5,
        decimal_places=2,
    )
    delivery_method = models.CharField(
        choices=DeliveryChoices.choices,
        verbose_name=_("delivery_method"),
        help_text=_("Required"),
        max_length=255,
    )
    delivery_timeframe = models.CharField(
        verbose_name=_("delivery timeframe"),
        help_text=_("Required"),
        max_length=255,
    )
    delivery_window = models.CharField(
        verbose_name=_("delivery window"),
        help_text=_("Required"),
        max_length=255,
    )
    order = models.IntegerField(verbose_name=_("list order"), help_text=_("Required"), default=0)
    is_active = models.BooleanField(default=True)

    class Meta:
        verbose_name = _("Delivery Option")
        verbose_name_plural = _("Delivery Options")

    def __str__(self):
        return self.delivery_name

checkout/views.py
import json
from django import contrib,  http
from django.shortcuts import render
from django.contrib.auth import decorators
from django.views.decorators import http as httpDecorators
from django.views.generic.base import TemplateView
from account import models as accountModels
from cart.cart import CartProcessor
from orders import models as orderModels
from checkout import models, payment
from cart import exceptions as cartExceptions
import requests


url = 'https://parseapi.back4app.com/classes/City?limit=5&order=-population,name&keys=name,country,countryCode,cityId,objectId'


@decorators.login_required
def deliveryChoices(request):
    deliveryOptions = models.DeliveryOptions.objects.filter(is_active=True)
    if deliveryOptions:
        cart = CartProcessor(request)
        updatedTotalPrice = cart.update_delivery(deliveryType=deliveryOptions[0])
    return render(request, "checkout/delivery_choices.html", {"deliveryOptions": deliveryOptions})


@httpDecorators.require_POST
@decorators.login_required
def cartUpdateDelivery(request):
    try:
        cart = CartProcessor(request)
        deliveryOption = int(request.POST.get("delivery_option"))
        deliveryType = models.DeliveryOptions.objects.get(id=deliveryOption)
        updatedTotalPrice = cart.update_delivery(deliveryType=deliveryType)

        session = request.session
        if "purchase" not in request.session:
            session["purchase"] = {
                "delivery_id": deliveryType.id,
            }
        else:
            session["purchase"]["delivery_id"] = deliveryType.id
            session.modified = True

        return http.JsonResponse({"total": updatedTotalPrice, "delivery_price": deliveryType.delivery_price})
    except models.DeliveryOptions.DoesNotExist:
        return http.HttpResponseNotFound("Delivery option not found")
    except cartExceptions.CartException as err:
        return http.HttpResponseBadRequest(err.message)



@decorators.login_required
def deliveryAddress(request):

    session = request.session
    if "purchase" not in request.session:
        contrib.messages.success(request, "Please select delivery option")
        return http.HttpResponseRedirect(request.META["HTTP_REFERER"])

    addresses = accountModels.Address.objects.filter(account=request.user).order_by("-default")

    if "address" not in request.session:
        session["address"] = {"address_id": str(addresses[0].id)}
    else:
        session["address"]["address_id"] = str(addresses[0].id)
        session.modified = True

    return render(request, "checkout/delivery_address.html", {"addresses": addresses})


@decorators.login_required
def paymentSelection(request):

    if "address" not in request.session:
        contrib.messages.warning(request, "Please select address option")
        return http.HttpResponseRedirect(request.META["HTTP_REFERER"])

    cart = CartProcessor(request)
    total = str(cart.get_total_price)
    total = int(total.replace('.', ''))

    paymentInstance = payment.paymentSystems[payment.PaymentOptions.CARD]
    
    paymentData = paymentInstance.get_or_create_item(userId=request.user.id, data=payment.PaymentData(amount=total, currency="usd", cart_id=cart.cart_id))
    
    cities = json.loads(requests.get(url, headers={
            'X-Parse-Application-Id': 'gJ1k7hOymzwNd0uAzWEquCYG7pI53yGaGwzxRdPi', 
            'X-Parse-Master-Key': '0uAjGdZmuqtoiTpbFTiMj1jpMNmr0lWhREtyyCjM'
        }).content.decode('utf-8'))

    return render(request, 'checkout/payment_selection.html', {"paymentData": paymentData, "paymentOptions": payment.PaymentOptions, "paymentInstance": paymentInstance, "cities":cities["results"], 'cart': cart})


@decorators.login_required
@httpDecorators.require_GET
def paymentSuccessful(request):
    try:
        paymentId = request.GET.get("payment_id", None)
        paymentInstance = payment.paymentSystems[payment.PaymentOptions.CARD]
        if paymentInstance.succeeded(paymentId):
            contrib.messages.success(request, "Payment Successful")
            return render(request, "checkout/payment_successful.html")
        return http.HttpResponseNotFound("Order not found")   
    except orderModels.Order.DoesNotExist:
        return http.HttpResponseNotFound("Order not found")   
    except cartExceptions.CartException as err:
        return http.HttpResponseBadRequest(err.message)        
    
class Error(TemplateView):
    template_name = 'checkout/error.html'

checkout/templates/checkout/delivery_address.html
{% extends "app.html" %}
{% load static %}
{% block title %}Cart Summary{%endblock %}
{% block content %}

<div class="container py-4 text-light">
  <div class="col-12">
    <h1 class="h2">Delivery Address</h1>
  </div>
  <div class="col-12">
    <p>Please select your delivery address</p>
  </div>
  <hr />
</div>


<div class="container ">
  <div class="row g-3">
    {% if addresses|length == 0 %}
    <div class="col-12">There are no delivery addresses, <a href="{% url 'account:add_address' %}">add address</a></div>
    {% else %}
    <div class="col-md-4 col-lg-4 order-md-last p-0 order-3 text-light">

      <div class="d-flex bd-highlight ms-0">
        <div class="p-2 flex-grow-1 bd-highlight">Sub Total:</div>
        <div class="p-2 bd-highlight"><span class="fw-bold h5">£</span><span id="sub_total"
            class="fw-bold h5">{{cart.get_subtotal_price}}</span></div>
      </div>
      <div class="d-flex bd-highlight">
        <div class="p-2 flex-grow-1 bd-highlight">Delivery Cost:</div>
        <div class="p-2 bd-highlight"><span class="fw-bold h5">£</span><span id="delivery_price"
            class="fw-bold h5">{{cart.get_delivery_price}}</span></div>
      </div>
      <div class="d-flex bd-highlight">
        <div class="p-2 flex-grow-1 bd-highlight">Total:</div>
        <div class="p-2 bd-highlight"><span class="fw-bold h5">£</span><span id="total"
            class="fw-bold h5">{{cart.get_total_price}}</span></div>
      </div>
      <a role="button" href="{% url 'checkout:payment_selection' %}" class="btn btn-success fw-bold w-100"
        type="button">Pay Securely</a>
    </div>

    <div class="col-md-7 col-lg-8">
      {% for address in addresses %}
      {% if not address.default %}
      <h1 class="h5 text-light mt-4">Other Addresses</h1>
      {% endif %}
      <div class="card mb-3 border-1 rounded-0 product-item me-md-4" data-index="{{option.id}}">
        <div class="row g-0">
          <div class="col">
            <div class="card pb-3 rounded-0">
              <div class="card-header bg-white small text-muted">
                {% if address.default %}
                Selected
                {% endif %}
                &nbsp;
              </div>
              <div class="card-body small pb-1">
                <p class="card-text m-0 fw-bold">{{address.full_name}}</p>
                <p class="card-text m-0">{{address.address_line}}</p>
                <p class="card-text m-0">{{address.address_line2}}</p>
                <p class="card-text m-0">{{address.town_city}}</p>
                <p class="card-text m-0">{{address.postcode}}</p>
                <p class="card-text m-0">Phone number: {{address.phone}}</p>
                <div class="pt-5">
                  <a href="{% url 'account:edit_address' address.id %}" class="text-decoration-none">Edit</a>
                  {% if not address.default %}
                  | <a href="{% url 'account:set_default_address' address.id %}" class="text-decoration-none">Select</a>
                  {% endif %}
                </div>
              </div>
            </div>
            </a>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
    {% endif %}
  </div>

</div>
{% endblock %}

checkout/templates/checkout/delivery_choices.html
{% extends "app.html" %}
{% load static %}
{% block title %}Delivery Options{%endblock %}
{% block content %}

<div class="container py-4 text-light">
  <div class="col-12">
    <h1 class="h2">Delivery Options</h1>
  </div>
  <div class="col-12">
    <p>Select your delivery options</p>
  </div>
  <hr />
</div>


<div class="container py-4">
{% if messages %}
<div class="alert alert-warning" alert-{{ message.tags }} role="alert">
  {% for message in messages  %}
    {{message|safe}}
  {% endfor %}
</div>
{% endif %}
  <div class="row g-3">
    {% if deliveryOptions|length == 0 %}
    <div class="col-12">There are no delivery options <a href="{% url 'store:products' %}">Shop</a></div>
    {% else %}
    <div class="col-md-4 col-lg-4 order-md-last p-0 order-3 text-light">
      <div class="d-flex bd-highlight ms-0">
        <div class="p-2 flex-grow-1 bd-highlight">Sub Total:</div>
        <div class="p-2 bd-highlight"><span class="fw-bold h5">£</span><span id="sub_total"
            class="fw-bold h5">{{cart.get_subtotal_price}}</span></div>
      </div>
      <div class="d-flex bd-highlight">
        <div class="p-2 flex-grow-1 bd-highlight">Delivery Cost:</div>
        <div class="p-2 bd-highlight"><span class="fw-bold h5">£</span><span id="delivery_price"
            class="fw-bold h5">{{cart.get_delivery_price}}</span></div>
      </div>
      <div class="d-flex bd-highlight">
        <div class="p-2 flex-grow-1 bd-highlight">Total:</div>
        <div class="p-2 bd-highlight"><span class="fw-bold h5">£</span><span id="total"
            class="fw-bold h5">{{cart.get_total_price}}</span></div>
      </div>
      <a role="button" href="{% url "checkout:delivery_address" %}" class="btn btn-success fw-bold w-100"
        type="button">Pay Securely</a>
    </div>
    <div class="col-md-7 col-lg-8">
      {% for option in deliveryOptions %}
      <div class="card text-bg-warning mb-3 border-1 rounded-0 product-item me-md-4" data-index="{{option.id}}">
        <div class="row g-0">
          <div class="col-md-2 ps-3 ps-md-4">
            <svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" fill="currentColor" class="bi bi-truck mt-2"
              viewBox="0 0 16 16">
              <path
                d="M0 3.5A1.5 1.5 0 0 1 1.5 2h9A1.5 1.5 0 0 1 12 3.5V5h1.02a1.5 1.5 0 0 1 1.17.563l1.481 1.85a1.5 1.5 0 0 1 .329.938V10.5a1.5 1.5 0 0 1-1.5 1.5H14a2 2 0 1 1-4 0H5a2 2 0 1 1-3.998-.085A1.5 1.5 0 0 1 0 10.5v-7zm1.294 7.456A1.999 1.999 0 0 1 4.732 11h5.536a2.01 2.01 0 0 1 .732-.732V3.5a.5.5 0 0 0-.5-.5h-9a.5.5 0 0 0-.5.5v7a.5.5 0 0 0 .294.456zM12 10a2 2 0 0 1 1.732 1h.768a.5.5 0 0 0 .5-.5V8.35a.5.5 0 0 0-.11-.312l-1.48-1.85A.5.5 0 0 0 13.02 6H12v4zm-9 1a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm9 0a1 1 0 1 0 0 2 1 1 0 0 0 0-2z" />
            </svg>
          </div>
          <div class="col-md-9 ps-md-1">
            <div class="card-body p-1">
              <label for="delivery-{{option.id}}" class="card-text ps-2 mb-1 pt-1 fw-bold">{{option.delivery_name}}</label>
              <p class="card-text ps-2 pb-3">Your order should be delivered within {{option.delivery_timeframe}}</p>
            </div>
          </div>
          <div class="col-md-1 ps-md-1">
            <input class="align-middle h-100" type="radio" name="deliveryOption" id="delivery-{{option.id}}"
              {% if option.id == cart.get_delivery_option %}checked{% endif %}
              value="{{option.id}}">
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
    {% endif %}
  </div>
</div>

{% endblock %}


{% block scripts %}
<script>
  $('input[type=radio][name=deliveryOption]').on('change', function(e) {
    e.preventDefault();
    $.ajax({
      type: "POST",
      url: '{% url "checkout:update_delivery" %}',
      data: {
        delivery_option: $(this).val(),
        csrfmiddlewaretoken: "{{csrf_token}}",
      },
      success: function (json) {
        document.getElementById("total").innerHTML = json.total;
        document.getElementById("delivery_price").innerHTML = json.delivery_price;
      },
      error: function (xhr, errmsg, err) {},
    });
    
  });
</script>
{% endblock  %}

checkout/templates/checkout/error.html
{% extends "app.html" %}
{% block title %}Order Error{% endblock %}
{% block content %}

<div class="container-fluid">

  <div class="p-4">
    <h3 class="mb-4">Error</h3>
    <p>Please contact our support team</p>
  </div>

</div>
{% endblock %}

checkout/templates/checkout/payment_selection.html
{% extends "app.html" %} {% load static %} {% block title %}Payment
Selection{%endblock %} {% block content %}

<div class="container py-4">
  <div class="row g-5">
    <div class="col-md-5 col-lg-4 order-md-last">
      <h4 class="d-flex justify-content-between align-items-center mb-3">
        <span class="text-light">Your cart</span>
        <span class="badge bg-primary rounded-pill">3</span>
      </h4>
      {% if cart|length == 0 %}
      <div><p>No product in the cart</p></div>
      {% else %}
      <ul class="list-group mb-3">
        {% for item in cart %} {% with product=item.product %}
        <li class="list-group-item d-flex justify-content-between lh-sm">
          <div>
            <h6 class="my-0">{{product.title}}</h6>
          </div>
          <span class="text-muted">{{item.quantity}}</span>
        </li>
        {% endwith %} {% endfor %}
  
        <li class="list-group-item d-flex justify-content-between lh-sm">
          <div>
            <h6 class="my-0">Sub Total</h6>
            <small class="text-muted"></small>
          </div>
          <span class="text-muted">${{cart.get_subtotal_price}}</span>
        </li>
        <li class="list-group-item d-flex justify-content-between bg-light">
          <div class="text-success">
            <h6 class="my-0">Delivery Cost</h6>
          </div>
          <span class="text-success">+${{cart.get_delivery_price}}</span>
        </li>
        <li class="list-group-item d-flex justify-content-between">
          <span>Total (USD)</span>
          <strong>${{cart.get_total_price}}</strong>
        </li>
      </ul>
      {% endif %}
    </div>
    <div class="col-md-7 col-lg-8">
      <div id="payment-form">
        <h3 class="mb-3 text-light">Billing address</h3>
        <!-- Error messages in this element -->
        <div id="card-errors" class="a" role="alert"></div>
        <form>
          <div class="row g-3">
            <div class="col-sm-7">
              <label for="firstName" class="form-label text-light">Customer Name</label>
              <input
                type="text"
                class="form-control"
                id="customerName"
                placeholder=""
                required
              />
              <div class="invalid-feedback">Valid first name is required.</div>
            </div>
            <div class="col-12">
              <label for="email" class="form-label text-light"
                >Email <span class="text-muted">(Optional)</span></label
              >
              <input
                type="email"
                class="form-control"
                id="email"
                placeholder="you@example.com"
              />
              <div class="invalid-feedback">
                Please enter a valid email address for shipping updates.
              </div>
            </div>
            <div class="col-12">
              <label for="phone" class="form-label text-light">Phone</label>
              <input
                type="text"
                class="form-control"
                id="customerPhone"
                placeholder="xxx xxx xx xx"
                required
              />
              <div class="invalid-feedback">Please enter your phone number.</div>
            </div>
            <div class="col-12">
              <label for="address" class="form-label text-light">Address</label>
              <input
                type="text"
                class="form-control"
                id="customerAddress"
                placeholder="1234 Main St"
                required
              />
              <div class="invalid-feedback">
                Please enter your shipping address.
              </div>
            </div>
            <div class="col-12">
              <label for="address2" class="form-label text-light"
                >Address 2 <span class="text-muted">(Optional)</span></label
              >
              <input
                type="text"
                class="form-control"
                id="customerAddress2"
                placeholder="Apartment or suite"
              />
            </div>
            <div class="col-md-4">
              <label for="city" class="form-label text-light">City</label>
              <select class="form-select" id="city" required>
                <option value="">Choose...</option>
                {% for city in cities %}
                <option value="{{city.name}}">{{city.name}}</option>
                {% endfor %}
              </select>
              <div class="invalid-feedback">Please provide a valid state.</div>
            </div>
            <div class="col-md-3">
              <label for="Postcode" class="form-label text-light">Postcode</label>
              <input
                type="text"
                class="form-control"
                id="postCode"
                placeholder=""
                required
              />
              <div class="invalid-feedback">Zip code required.</div>
            </div>
          </div>
          <hr class="my-4" />
          <h4 class="mb-3 text-light">Payment</h4>
          <label for="card-element text-light">Credit card</label>
          <div id="card-element" class="form-control form-control-payment">
            <!-- Payment elements will appear here -->
          </div>
          <hr class="my-4" />
          <button
            id="submit"
            class="btn btn-primary w-100 fw-bold"
            data-secret="{{ paymentData.client_secret }}"
          >
            Pay
          </button>
        </form>
      </div>
    </div>
  </div>
</div>

{% endblock %} {% block scripts %} {% if request.GET.payment_type == "paypal" %}
<script>
  console.log("paypal");
</script>
{% else %}
<script>
  var STRIPE_PUBLISHABLE_KEY = "{{paymentInstance.publishable_key}}";
  var CSRF_TOKEN = "{{ csrf_token }}";

  // Example starter JavaScript for disabling form submissions if there are invalid fields
  (() => {
    "use strict";

    // Fetch all the forms we want to apply custom Bootstrap validation styles to
    const forms = document.querySelectorAll(".needs-validation");

    // Loop over them and prevent submission
    Array.from(forms).forEach((form) => {
      form.addEventListener(
        "submit",
        (event) => {
          if (!form.checkValidity()) {
            event.preventDefault();
            event.stopPropagation();
          }

          form.classList.add("was-validated");
        },
        false
      );
    });
  })();
</script>
<script src="https://js.stripe.com/v3/"></script>
<script src="{% static 'js/payment.js' %}" data-rel-js></script>
{% endif %} {% endblock %}

checkout/templates/checkout/payment_successful.html
{% extends "app.html" %}
{% load static %}
{% block title %}Payment Successful{%endblock %}
{% block content %}

<div class="container py-4">
  <div class="p-5 mb-4 bg-light rounded-3">
    <div class="container-fluid py-5">
      <h1 class="display-5 fw-bold text-success">Payment Successful</h1>
      <h5 class="col-md-8 fs-4">Order Summary.</h5>
      <a href="{% url 'account:orders'%}" class="btn btn-primary btn-lg" type="button">View all orders</a>
    </div>
  </div>
</div>


{% endblock %}