account/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from django.views.generic import TemplateView

from . import views
from .forms import PwdResetConfirmForm, PwdResetForm, UserLoginForm

app_name = 'account'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='account/auth/login.html',
                                                form_class=UserLoginForm), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/account/login/'), name='logout'),
    path('register/', views.register, name='register'),
    path('activate/<slug:uidb64>/<slug:token>/', views.activate, name='activate'),
    # Reset password
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name="account/auth/password_reset_form.html",
                                                                 success_url='password_reset_email_confirm',
                                                                 email_template_name='account/auth/password_reset_email.html',
                                                                 form_class=PwdResetForm), name='pwdreset'),
    path('password_reset_confirm/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name='account/auth/password_reset_confirm.html',
                                                                                                success_url='password_reset_complete/',
                                                                                                form_class=PwdResetConfirmForm),
         name="password_reset_confirm"),
    path('password_reset/password_reset_email_confirm/',
         TemplateView.as_view(template_name="account/auth/password_reset_status.html"), name='password_reset_done'),
    path('password_reset_confirm/Mg/password_reset_complete/',
         TemplateView.as_view(template_name="account/auth/password_reset_status.html"), name='password_reset_complete'),

    path('dashboard/', views.dashboard, name='dashboard'),
    path('profile/edit/', views.edit, name='edit'),
    path('profile/delete/', views.delete, name='delete'),
    path('profile/delete_confirm/', TemplateView.as_view(template_name="account/user/delete_confirm.html"), name='delete_confirmation'),
    path("addresses/", views.addresses, name="addresses"),
    path("add_address/", views.addAddress, name="add_address"),
    path("addresses/edit/<slug:id>/", views.editAddress, name="edit_address"),
    path("addresses/delete/<slug:id>/", views.deleteAddress, name="delete_address"),
    path("addresses/set_default/<slug:id>/", views.setDefaultAddress, name="set_default_address"),
    path("wishlist/", views.wishlist, name="wishlist"),
    path("wishlist/toggle/<int:id>", views.addToWishlist, name="toggle_wishlist"),
    path("orders/", views.ordersView, name="orders"),
]

cart/urls.py
from django.urls import path

from cart import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart, name='cart'),
    path('add/', views.cartAdd, name='cart_add'),
    path('update/', views.cartUpdate, name='cart_update'),
    path('delete/', views.cartDelete, name='cart_delete'),
]

core/urls.py
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('orders/', include('orders.urls', namespace='orders')),
    path('shopping-cart/', include('cart.urls', namespace='cart')),
    path('account/', include('account.urls', namespace='account')),
    path('checkout/', include('checkout.urls', namespace='checkout')),
    path('', include('store.urls', namespace='store')),
    path("__debug__/", include(debug_toolbar.urls)),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path

from . import views

app_name = 'store'

urlpatterns = [
    path('', views.products, name='products'),
    path('<slug:slug>/', views.productDetail, name='product_detail'),
    path('shop/<slug:category_slug>/', views.categoryProducts, name='category_products'),
]

templates/app.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8" />
  <title>{% block title %}Book Store{% endblock %}</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="Content-Security-Policy" content="default-src *;
   img-src * 'self' data: https:; script-src 'self' 'unsafe-inline' 'unsafe-eval' *;
   style-src  'self' 'unsafe-inline' *">

  <!-- CSS only -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">

  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  {% block stylesheet %}{% endblock %}
</head>

<body>
  <header>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark border-bottom">
      <div class="container-fluid">
        <a class="navbar-brand" href="/">BookStore</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse"
          aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
          <ul class="navbar-nav me-auto mb-2 mb-md-0">
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Library
              </a>
              <ul class="dropdown-menu dropdown-menu-dark gap-1 p-2 rounded-3 mx-0 border-0 shadow">
                <li>
                  <a class="dropdown-item d-flex align-items-center gap-2 py-2" href="{% url "store:products" %}">
                    <span class="d-inline-block bg-success rounded-circle p-1"></span>
                    All
                  </a>
                </li>
                {% for c in categories %}
                <li {% if category.slug == c.slug %}class="selected" {% endif %}>
                  <a class="dropdown-item d-flex align-items-center gap-2 py-2" href="{{ c.get_absolute_url }}">
                    <span class="d-inline-block bg-danger rounded-circle p-1"></span>
                    {{ c.name|title }}
                  </a>
                </li>
                {% endfor %}
              </ul>
            </li>
          </ul>

          <ul class="navbar-nav mb-2 mb-md-0">
            {% if request.user.is_authenticated %}
            <li class="nav-item">
              <a type="button" role="button" href="{% url "account:logout" %}"
                class="nav-link btn btn-outline-danger border-0">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-box-arrow-left" viewBox="0 0 16 16">
                  <path fill-rule="evenodd" d="M6 12.5a.5.5 0 0 0 .5.5h8a.5.5 0 0 0 .5-.5v-9a.5.5 0 0 0-.5-.5h-8a.5.5 0 0 0-.5.5v2a.5.5 0 0 1-1 0v-2A1.5 1.5 0 0 1 6.5 2h8A1.5 1.5 0 0 1 16 3.5v9a1.5 1.5 0 0 1-1.5 1.5h-8A1.5 1.5 0 0 1 5 12.5v-2a.5.5 0 0 1 1 0v2z"/>
                  <path fill-rule="evenodd" d="M.146 8.354a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L1.707 7.5H10.5a.5.5 0 0 1 0 1H1.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3z"/>
                </svg>
                <span class="fw500">Logout</span>
              </a>
            </li>
            <li class="nav-item">
              <a type="button" role="button" href="{% url "account:wishlist" %}"
                class="nav-link btn btn btn-outline-success border-0">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-suit-heart-fill" viewBox="0 0 16 16">
                  <path d="M4 1c2.21 0 4 1.755 4 3.92C8 2.755 9.79 1 12 1s4 1.755 4 3.92c0 3.263-3.234 4.414-7.608 9.608a.513.513 0 0 1-.784 0C3.234 9.334 0 8.183 0 4.92 0 2.755 1.79 1 4 1z"/>
                </svg>
                <span class="fw500">Wishlist</span>
              </a>
            </li>
            <li class="nav-item">
              <a type="button" role="button" href="{% url "account:dashboard" %}"
                class="nav-link btn btn-outline-info border-0">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-fill" viewBox="0 0 16 16">
                  <path d="M3 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H3zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6z"/>
                </svg>
                <span class="fw500">Account</span>
              </a>
            </li>
            {% else %}
            <li class="nav-item">
              <a type="button" role="button" href="{% url "account:login" %}"
                class="nav-link btn btn-outline-info border-0">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-box-arrow-right" viewBox="0 0 16 16">
                  <path fill-rule="evenodd" d="M10 12.5a.5.5 0 0 1-.5.5h-8a.5.5 0 0 1-.5-.5v-9a.5.5 0 0 1 .5-.5h8a.5.5 0 0 1 .5.5v2a.5.5 0 0 0 1 0v-2A1.5 1.5 0 0 0 9.5 2h-8A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h8a1.5 1.5 0 0 0 1.5-1.5v-2a.5.5 0 0 0-1 0v2z"/>
                  <path fill-rule="evenodd" d="M15.854 8.354a.5.5 0 0 0 0-.708l-3-3a.5.5 0 0 0-.708.708L14.293 7.5H5.5a.5.5 0 0 0 0 1h8.793l-2.147 2.146a.5.5 0 0 0 .708.708l3-3z"/>
                </svg>
                <span class="fw500">Login</span>
              </a>
            </li>
            {% endif %}
            <a type="button" role="button" href="{% url "cart:cart" %}" class="mx-2 btn btn-outline-warning">

              {% with total_quantity=cart|length %}
              <div id="cart-quantity" class="d-inline-flex">
                {% if total_quantity > 0 %}
                {{ total_quantity }}
                {% else %}
                0
                {% endif %}
              </div>
              {% endwith %}
  
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-cart3"
                viewBox="0 0 16 16">
                <path
                  d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .49.598l-1 5a.5.5 0 0 1-.465.401l-9.397.472L4.415 11H13a.5.5 0 0 1 0 1H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l.84 4.479 9.144-.459L13.89 4H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z" />
              </svg>
              Cart
            </a>
          </ul>

          

          
        </div>
        <div class="d-md-none d-lg-none d-xl-none">
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav me-auto mb-2 mb-md-0">
              <li><a class="dropdown-item" href="{% url "store:products" %}">All</a></li>
              {% for c in categories %}
              <li {% if category.slug == c.slug %}class="selected" {% endif %}>
                <a class="dropdown-item" href="{{ c.get_absolute_url }}">{{ c.name|title }}</a>
              </li>
              {% endfor %}
            </ul>
          </div>
        </div>
      </div>
    </nav>
  </header>
  
  <main id="content py-5">
    {% block content %} {% endblock %}
  </main>


  <script src="https://code.jquery.com/jquery-3.6.0.min.js"
    integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous">
  </script>


  <div id="scripts">
    {% block scripts %} {% endblock %}
  </div>

</body>

</html>